-- CreateTable
CREATE TABLE "Kol" (
    "id" SERIAL NOT NULL,
    "twitter_bind" BOOLEAN NOT NULL,
    "twitter_url" TEXT NOT NULL,
    "twitter_fans_num" INTEGER NOT NULL,
    "twitter_username" TEXT NOT NULL,
    "twitter_name" TEXT NOT NULL,
    "ens" TEXT,
    "avatar" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "balance" TEXT,
    "total_value" DOUBLE PRECISION,
    "unrealized_profit" DOUBLE PRECISION,
    "unrealized_pnl" DOUBLE PRECISION,
    "realized_profit" DOUBLE PRECISION,
    "pnl" DOUBLE PRECISION,
    "pnl_1d" DOUBLE PRECISION,
    "pnl_7d" DOUBLE PRECISION,
    "pnl_30d" DOUBLE PRECISION,
    "realized_profit_1d" DOUBLE PRECISION,
    "realized_profit_7d" DOUBLE PRECISION,
    "realized_profit_30d" DOUBLE PRECISION,
    "winrate" DOUBLE PRECISION,
    "all_pnl" DOUBLE PRECISION,
    "total_profit" DOUBLE PRECISION,
    "total_profit_pnl" DOUBLE PRECISION,
    "buy_1d" DOUBLE PRECISION,
    "sell_1d" DOUBLE PRECISION,
    "buy_7d" DOUBLE PRECISION,
    "sell_7d" DOUBLE PRECISION,
    "buy_30d" DOUBLE PRECISION,
    "sell_30d" DOUBLE PRECISION,
    "buy" DOUBLE PRECISION,
    "sell" DOUBLE PRECISION,
    "history_bought_cost" DOUBLE PRECISION,
    "token_avg_cost" DOUBLE PRECISION,
    "token_sold_avg_profit" DOUBLE PRECISION,
    "token_num" INTEGER,
    "profit_num" INTEGER,
    "pnl_lt_minus_dot5_num" INTEGER,
    "pnl_minus_dot5_0x_num" INTEGER,
    "pnl_lt_2x_num" INTEGER,
    "pnl_2x_5x_num" INTEGER,
    "pnl_gt_5x_num" INTEGER,
    "last_active_timestamp" INTEGER,
    "tags" TEXT[],
    "tag_rank" JSONB NOT NULL,
    "followers_count" INTEGER,
    "is_contract" BOOLEAN,
    "updated_at" INTEGER,
    "refresh_requested_at" INTEGER,
    "avg_holding_peroid" DOUBLE PRECISION,

    CONSTRAINT "Kol_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Trade" (
    "id" SERIAL NOT NULL,
    "kolId" INTEGER NOT NULL,
    "balance" TEXT,
    "usd_value" TEXT,
    "realized_profit_30d" TEXT,
    "realized_profit" TEXT,
    "realized_pnl" TEXT,
    "realized_pnl_30d" TEXT,
    "unrealized_profit" TEXT,
    "unrealized_pnl" TEXT,
    "total_profit" TEXT,
    "total_profit_pnl" TEXT,
    "avg_cost" TEXT,
    "avg_sold" TEXT,
    "buy_30d" INTEGER,
    "sell_30d" INTEGER,
    "sells" INTEGER,
    "price" TEXT,
    "cost" TEXT,
    "position_percent" TEXT,
    "last_active_timestamp" INTEGER,
    "history_sold_income" TEXT,
    "history_bought_cost" TEXT,
    "start_holding_at" INTEGER,
    "end_holding_at" INTEGER,
    "liquidity" TEXT,
    "wallet_token_tags" JSONB,

    CONSTRAINT "Trade_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Kol_twitter_username_key" ON "Kol"("twitter_username");

-- AddForeignKey
ALTER TABLE "Trade" ADD CONSTRAINT "Trade_kolId_fkey" FOREIGN KEY ("kolId") REFERENCES "Kol"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
